# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2026 Pavel Círus, Jan Dvořáček
# Copyright (C) 1996-2026 SCS Software s.r.o.



schema_version = "1.0.0"

id = "scs_asset_toolkit"
version = "0.0.3"
name = "SCS Asset Toolkit"
tagline = "LOD, Shadow & Collision generation toolkit for assets"
maintainer = """\
    Pavel Círus (Paul) <pavel.cirus@scssoft.com>, \
    Jan Dvořáček <jan.dvoracek@scssoft.com>\
    """

type = "add-on"

blender_version_min = "5.0.1"

license = ["SPDX:GPL-3.0-or-later"]

copyright = [
    "2026 Pavel Círus, Jan Dvořáček, All Rights Reserved.",
    "1996-2026 SCS Software s.r.o., All Rights Reserved.",
]
 
tags = ["Mesh", "Object"]
 
[build]
paths_exclude_pattern = [
    "*.blend1",
    "__pycache__/",
    ".*",
    "*.zip",
    "*.ps1",
    ".build_number",
    "*.code-workspace",
    ".vscode/",
]
